version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/user_db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m unittest discover tests
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/test_db
    depends_on:
      - mongodb

volumes:
  mongodb_data: